/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMarketplaceRouteImport } from './routes/settings.marketplace'
import { Route as SettingsDeveloperRouteImport } from './routes/settings.developer'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardHubRouteImport } from './routes/dashboard.hub'
import { Route as DashboardAutomationRouteImport } from './routes/dashboard.automation'
import { Route as DashboardAiStudioRouteImport } from './routes/dashboard.ai-studio'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminChannelsRouteImport } from './routes/admin.channels'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiPublicChannelsChannelIdInboundRouteImport } from './routes/api/public/channels.$channelId.inbound'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMarketplaceRoute = SettingsMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDeveloperRoute = SettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHubRoute = DashboardHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationRoute = DashboardAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiStudioRoute = DashboardAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/admin/channels',
  path: '/admin/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChannelsChannelIdInboundRoute =
  ApiPublicChannelsChannelIdInboundRouteImport.update({
    id: '/api/public/channels/$channelId/inbound',
    path: '/api/public/channels/$channelId/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/queues': typeof QueuesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/supervisor': typeof SupervisorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/dashboard/ai-studio': typeof DashboardAiStudioRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/hub': typeof DashboardHubRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/marketplace': typeof SettingsMarketplaceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/channels/$channelId/inbound': typeof ApiPublicChannelsChannelIdInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/queues': typeof QueuesRoute
  '/reports': typeof ReportsRoute
  '/supervisor': typeof SupervisorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/dashboard/ai-studio': typeof DashboardAiStudioRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/hub': typeof DashboardHubRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/marketplace': typeof SettingsMarketplaceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/channels/$channelId/inbound': typeof ApiPublicChannelsChannelIdInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/queues': typeof QueuesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/supervisor': typeof SupervisorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/dashboard/ai-studio': typeof DashboardAiStudioRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/hub': typeof DashboardHubRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/marketplace': typeof SettingsMarketplaceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/channels/$channelId/inbound': typeof ApiPublicChannelsChannelIdInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/knowledge'
    | '/opportunities'
    | '/queues'
    | '/reports'
    | '/settings'
    | '/supervisor'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/companies'
    | '/dashboard/ai-studio'
    | '/dashboard/automation'
    | '/dashboard/hub'
    | '/dashboard/notifications'
    | '/settings/billing'
    | '/settings/developer'
    | '/settings/marketplace'
    | '/settings/notifications'
    | '/settings/profile'
    | '/dashboard/'
    | '/settings/'
    | '/api/public/channels/$channelId/inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/crm'
    | '/customers'
    | '/inbox'
    | '/knowledge'
    | '/opportunities'
    | '/queues'
    | '/reports'
    | '/supervisor'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/companies'
    | '/dashboard/ai-studio'
    | '/dashboard/automation'
    | '/dashboard/hub'
    | '/dashboard/notifications'
    | '/settings/billing'
    | '/settings/developer'
    | '/settings/marketplace'
    | '/settings/notifications'
    | '/settings/profile'
    | '/dashboard'
    | '/settings'
    | '/api/public/channels/$channelId/inbound'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campaigns'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/knowledge'
    | '/opportunities'
    | '/queues'
    | '/reports'
    | '/settings'
    | '/supervisor'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/companies'
    | '/dashboard/ai-studio'
    | '/dashboard/automation'
    | '/dashboard/hub'
    | '/dashboard/notifications'
    | '/settings/billing'
    | '/settings/developer'
    | '/settings/marketplace'
    | '/settings/notifications'
    | '/settings/profile'
    | '/dashboard/'
    | '/settings/'
    | '/api/public/channels/$channelId/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  CrmRoute: typeof CrmRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InboxRoute: typeof InboxRoute
  KnowledgeRoute: typeof KnowledgeRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  QueuesRoute: typeof QueuesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupervisorRoute: typeof SupervisorRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  ApiPublicChannelsChannelIdInboundRoute: typeof ApiPublicChannelsChannelIdInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/marketplace': {
      id: '/settings/marketplace'
      path: '/marketplace'
      fullPath: '/settings/marketplace'
      preLoaderRoute: typeof SettingsMarketplaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/developer': {
      id: '/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof SettingsDeveloperRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hub': {
      id: '/dashboard/hub'
      path: '/hub'
      fullPath: '/dashboard/hub'
      preLoaderRoute: typeof DashboardHubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automation': {
      id: '/dashboard/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof DashboardAutomationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-studio': {
      id: '/dashboard/ai-studio'
      path: '/ai-studio'
      fullPath: '/dashboard/ai-studio'
      preLoaderRoute: typeof DashboardAiStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/admin/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channels/$channelId/inbound': {
      id: '/api/public/channels/$channelId/inbound'
      path: '/api/public/channels/$channelId/inbound'
      fullPath: '/api/public/channels/$channelId/inbound'
      preLoaderRoute: typeof ApiPublicChannelsChannelIdInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiStudioRoute: typeof DashboardAiStudioRoute
  DashboardAutomationRoute: typeof DashboardAutomationRoute
  DashboardHubRoute: typeof DashboardHubRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiStudioRoute: DashboardAiStudioRoute,
  DashboardAutomationRoute: DashboardAutomationRoute,
  DashboardHubRoute: DashboardHubRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsDeveloperRoute: typeof SettingsDeveloperRoute
  SettingsMarketplaceRoute: typeof SettingsMarketplaceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsDeveloperRoute: SettingsDeveloperRoute,
  SettingsMarketplaceRoute: SettingsMarketplaceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  CrmRoute: CrmRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InboxRoute: InboxRoute,
  KnowledgeRoute: KnowledgeRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  QueuesRoute: QueuesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupervisorRoute: SupervisorRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  ApiPublicChannelsChannelIdInboundRoute:
    ApiPublicChannelsChannelIdInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
